



































































































[30;1m2023-05-03 10:28:57[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-05-03 10:28:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: a0af072d9050f50315ae59150f259a6b).










[30;1m2023-05-03 10:32:04[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-05-03 10:32:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: dc92cf0fb256e0e8570d50058161bc09).
[30;1m2023-05-03 10:32:10[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "C:\Users\philip.kullen.LEARNET\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\philip.kullen.LEARNET\Desktop\Programering\NTI-Website\python\bot\bot.py", line 47, in on_message
    print(message.author.guild)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'guild'[0m
[30;1m2023-05-03 10:32:23[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "C:\Users\philip.kullen.LEARNET\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\philip.kullen.LEARNET\Desktop\Programering\NTI-Website\python\bot\bot.py", line 47, in on_message
    print(message.author.guild)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'guild'[0m
[30;1m2023-05-03 10:32:24[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "C:\Users\philip.kullen.LEARNET\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\philip.kullen.LEARNET\Desktop\Programering\NTI-Website\python\bot\bot.py", line 47, in on_message
    print(message.author.guild)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'guild'[0m
[30;1m2023-05-03 10:32:24[0m [31mERROR   [0m [35mdiscord.client[0m Ignoring exception in on_message
[31mTraceback (most recent call last):
  File "C:\Users\philip.kullen.LEARNET\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\philip.kullen.LEARNET\Desktop\Programering\NTI-Website\python\bot\bot.py", line 47, in on_message
    print(message.author.guild)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'guild'[0m


















































